### ISSUE TITLE
Creating a ZSH mode

### ISSUE THREAD

**Issue by CleanMachine1** [CleanMachine1/DollarSkip#28]
ZSH uses %, simple change.

Yet I have never seen a guide using ZSH instead of bash.

Would be simple to implement with just making the file name /usr/bin/%

**Comment by Itai-Nelken** [comment]
something like this in the makefile should work:
```bash
case $SHELL in
    bash) sudo cp temp /usr/bin/\$ ;;
    zsh) sudo cp temp /usr/bin\% ;;
    *) echo "ERROR: unkown shell!"; exit 1 ;;
esac
```

**Comment by Itai-Nelken** [comment]
or we could make a script that runs on shell startup (using `~/.bashrc` or equivalent) that renames `/usr/bin/$` to whatever is needed for the current shell.

**Comment by CleanMachine1** [comment]
The makefile is how I thought of it.

However most guides use $ so that should always install $.

Maybe just a new makefile command called zsh moving the binary to the correct name and path

**Comment by Itai-Nelken** [comment]
The zsh target for the makefile sounds good to me

**Comment by CleanMachine1** [comment]
Do we want ZSH version to always be a part of it, by making the `sudo make install` command do it or just for users that specifically install it?

**Comment by Itai-Nelken** [comment]
I think that only users who specifically install it. most tutorials are for bash, so they have `$` and the dollar sign is also used for shells in general I think.
so we can add a `zsh` target but its optional.

**Comment by LoganDark** [comment]
> However most guides use $sothatshouldalwaysinstall$.

Oh my god GitHub supports MathJax.

**Comment by CleanMachine1** [comment]
:smile:
