### ISSUE TITLE
suggestion for the github actions workflow

### ISSUE THREAD

**Issue by Itai-Nelken** [CleanMachine1/DollarSkip#3]
you don't need those 2 lines: 
https://github.com/CleanMachine1/DollarSkip/blob/42f5bb1c5ebcc2567f4532bb2c544d5db607a0d6/.github/workflows/main.yml#L28-L29
the checkout action does that already.

**Comment by Itai-Nelken** [comment]
btw i just realized that you have unlimited github actions minutes for public repositories!

**Comment by CleanMachine1** [comment]
I didn't actually mean to leave it there, it was only me compiling on a different computer to test

**Comment by CleanMachine1** [comment]
> btw i just realized that you have unlimited github actions minutes for public repositories!

cool

**Comment by Itai-Nelken** [comment]
also congratulations on becoming a tldr maintainer!

**Comment by CleanMachine1** [comment]
https://github.com/CleanMachine1/DollarSkip/runs/2591397067?check_suite_focus=true

**Comment by Itai-Nelken** [comment]
you already are inside the repo. just run `make test` and you are done.

**Comment by CleanMachine1** [comment]
fixed
Thanks
