### ISSUE TITLE
Hash sign support

### ISSUE THREAD

**Issue by BulletBlaster** [CleanMachine1/DollarSkip#38]
Some guides (for example the Arch Wiki) in addition to the dollar sign use the hash sign to indicate that the command has to be run as root.

I think it should be easy to make it work almost the same as a dollar sign, just prefixing the command with sudo (or optionally doas, this could be a Makefile option)

**Comment by CleanMachine1** [comment]
Ive just had another thought after reading this again, while I really do like all of the contributions, I think I am going to have to decline this. 

Executing potential comments is a bad idea, and replacing it with sudo is even worse.

However if you would like yourself. I am sure you can create a synbolic link from a file called # to $(whereis sudo)
